---
- hosts: localhost
  gather_facts: false

  vars_files:
    - vars/main.yml

  tasks:
    - name: Deploy WordPress secrets.
      k8s:
        definition: '{{ item }}'
        kubeconfig: '{{ k8s_kubeconfig }}'
        state: present
      loop: "{{ lookup('template', 'wordpress/mysql-pass.yml') | from_yaml_all | list }}"
      no_log: k8s_no_log

    - name: Deploy MySQL and WordPress.
      k8s:
        definition: '{{ item }}'
        kubeconfig: '{{ k8s_kubeconfig }}'
        state: present
      loop:
        - "{{ lookup('template', 'wordpress/mysql.yml') | from_yaml_all | list }}"
        - "{{ lookup('template', 'wordpress/wordpress.yml') | from_yaml_all | list }}"


